## Creating all Breed instances

Breed.create!(name: 'Affenpinscher', size: 0, medium_weight: "3-4kg")
Breed.create!(name: 'Bichon Frisé', size: 0, medium_weight: "2,5-3kg")
Breed.create!(name: 'Bichon Havanês', size: 0, medium_weight: "3-5,5kg")
Breed.create!(name: 'Cão de Crista Chinês', size: 0, medium_weight: "2,3-5,4kg")
Breed.create!(name: 'Cavalier King Charles Spaniel', size: 0, medium_weight: "5-9kg")
Breed.create!(name: 'Chihuahua', size: 0, medium_weight: "0,5-3kg")
Breed.create!(name: 'Coton de Tulear', size: 0, medium_weight: "3,5-6kg")
Breed.create!(name: 'Griffon de Bruxelas', size: 0, medium_weight: "4,5-5,5kg")
Breed.create!(name: 'Lulu da Pomerânia/Spitz Alemão Anão', size: 0, medium_weight: "1,9-3,5kg")
Breed.create!(name: 'Maltês', size: 0, medium_weight: "3-4kg")
Breed.create!(name: 'Norfolk Terrier', size: 0, medium_weight: "5-5,4kg")
Breed.create!(name: 'Norwich Terrier', size: 0, medium_weight: "5-5,4kg")
Breed.create!(name: 'Pappilon/Spaniel anão continental', size: 0, medium_weight: "3-4,5kg")
Breed.create!(name: 'Pinscher miniatura', size: 0, medium_weight: "3,5-5kg")
Breed.create!(name: 'Poodle Toy', size: 0, medium_weight: "3-6kg")
Breed.create!(name: 'Sliky Terrier Australiano', size: 0, medium_weight: "3,5-4,5kg")
Breed.create!(name: 'Terrier Australiano', size: 0, medium_weight: "3,6-6,3kg")
Breed.create!(name: 'Volpino Italiano', size: 0, medium_weight: "4-5kg")
Breed.create!(name: 'Yorkshire', size: 0, medium_weight: "2,5-3,5kg")
Breed.create!(name: 'Basenji', size: 1, medium_weight: "9-11kg")
Breed.create!(name: 'Dachshund/Teckel', size: 1, medium_weight: "7,5-15kg")
Breed.create!(name: 'Beagle', size: 1, medium_weight: "8-14kg")
Breed.create!(name: 'Bedlington Terrier', size: 1, medium_weight: "7,7-10,5kg")
Breed.create!(name: 'Boston Terrier', size: 1, medium_weight: "7-11kg")
Breed.create!(name: 'Bulldog Francês', size: 1, medium_weight: "8-14kg")
Breed.create!(name: 'Cairn Terrier', size: 1, medium_weight: "6-8kg")
Breed.create!(name: 'Cesky Terrier', size: 1, medium_weight: "6-10kg")
Breed.create!(name: 'Cocker Spaniel Americano', size: 1, medium_weight: "7-14kg")
Breed.create!(name: 'Cocker Spaniel Inglês', size: 1, medium_weight: "12-16kg")
Breed.create!(name: 'Dandie Dinmont Terrier', size: 1, medium_weight: "8-11kg")
Breed.create!(name: 'Fox Paulistinha/Terrier Brasileiro', size: 1, medium_weight: "6,5-10kg")
Breed.create!(name: 'Fox Terrier de pelo liso', size: 1, medium_weight: "7-8kg")
Breed.create!(name: 'Jack Russell Terrier', size: 1, medium_weight: "6,4-8,2kg")
Breed.create!(name: 'Lakeland Terrier', size: 1, medium_weight: "7-8kg")
Breed.create!(name: 'Lhasa Apso', size: 1, medium_weight: "5-8kg")
Breed.create!(name: 'Mudi', size: 1, medium_weight: "8-13kg")
Breed.create!(name: 'Pastor de Shetland', size: 1, medium_weight: "5-12g")
Breed.create!(name: 'Galguinho Italiano/Pequeno Lebrel italiano', size: 1, medium_weight: "3,6-5kg")
Breed.create!(name: 'Pequinês', size: 1, medium_weight: "3-6,4kg")
Breed.create!(name: 'Poodle anão', size: 1, medium_weight: "7kg")
Breed.create!(name: 'Pug', size: 1, medium_weight: "6-8kg")
Breed.create!(name: 'Schanauzer miniatura', size: 1, medium_weight: "5-9kg")
Breed.create!(name: 'Schipperke', size: 1, medium_weight: "3-9kg")
Breed.create!(name: 'Scottish Terrier', size: 1, medium_weight: "8-10kg")
Breed.create!(name: 'Sealyham Terrier', size: 1, medium_weight: "8-9kg")
Breed.create!(name: 'Shiba inu', size: 1, medium_weight: "6-11kg")
Breed.create!(name: 'Shih-tzu', size: 1, medium_weight: "4-7,2kg")
Breed.create!(name: 'Skye Terrier', size: 1, medium_weight: "12-18kg")
Breed.create!(name: 'Terrier Irlandes do Glen do Imaal', size: 1, medium_weight: "14-16kg")
Breed.create!(name: 'Tibetan Terrier', size: 1, medium_weight: "8-14kg")
Breed.create!(name: 'Welsh Corgi Cardigan', size: 1, medium_weight: "11-17kg")
Breed.create!(name: 'Welsh Corgi Pembroke', size: 1, medium_weight: "10-14kg")
Breed.create!(name: 'Welsh Terrier', size: 1, medium_weight: "9-10kg")
Breed.create!(name: 'West Highland White Terrier', size: 1, medium_weight: "6-10kg")
Breed.create!(name: 'American Staffordshire Terrier', size: 2, medium_weight: "28-40kg")
Breed.create!(name: 'Basset Hound', size: 2, medium_weight: "20-29kg")
Breed.create!(name: 'Bearded Collie', size: 2, medium_weight: "18-27kg")
Breed.create!(name: 'Boiadeiro-australiano/Australian Cattle Dog', size: 2, medium_weight: "14-16kg")
Breed.create!(name: 'Border Collie', size: 2, medium_weight: "12-20kg")
Breed.create!(name: 'Bull Terrier', size: 2, medium_weight: "22-38kg")
Breed.create!(name: 'Bulldog Inglês', size: 2, medium_weight: "18-25kg")
Breed.create!(name: "Cão d'água Espanhol", size: 2, medium_weight: "12-20kg")
Breed.create!(name: "Cão d'água Português", size: 2, medium_weight: "16-25kg")
Breed.create!(name: 'Cão Pelado Peruano', size: 2, medium_weight: "8-12kg")
Breed.create!(name: 'Chow-chow', size: 2, medium_weight: "20-35kg")
Breed.create!(name: 'Cirneco do Etna', size: 2, medium_weight: "8-12kg")
Breed.create!(name: 'Hokkaido', size: 2, medium_weight: "20-30kg")
Breed.create!(name: 'Irish Soft Coated Wheaten Terrier', size: 2, medium_weight: "14-18kg")
Breed.create!(name: 'Kerry BlueTerrier', size: 2, medium_weight: "15-18kg")
Breed.create!(name: 'Lagotto Romagnolo', size: 2, medium_weight: "11-16kg")
Breed.create!(name: 'Pastor Australiano', size: 2, medium_weight: "16-30kg")
Breed.create!(name: 'Pastor dos Pirineus', size: 2, medium_weight: "8-15kg")
Breed.create!(name: 'Pastor Polonês da Planície', size: 2, medium_weight: "14-20kg")
Breed.create!(name: 'Pinscher Alemão', size: 2, medium_weight: "11-20kg")
Breed.create!(name: 'Poodle médio', size: 2, medium_weight: "12kg")
Breed.create!(name: 'Puli', size: 2, medium_weight: "10-15kg")
Breed.create!(name: 'Pumi', size: 2, medium_weight: "8-15kg")
Breed.create!(name: 'Schnauzer standard', size: 2, medium_weight: "14-20kg")
Breed.create!(name: 'Shar-pei', size: 2, medium_weight: "18-30kg")
Breed.create!(name: 'Spaniel Bretão', size: 2, medium_weight: "14-18kg")
Breed.create!(name: 'Springer Spaniel Inglês', size: 2, medium_weight: "18-25kg")
Breed.create!(name: 'Staffordshire Bull Terrier', size: 2, medium_weight: "11-17kg")
Breed.create!(name: 'Whippet', size: 2, medium_weight: "7-14kg")
Breed.create!(name: 'Airedale Terrier', size: 3, medium_weight: "18-29kg")
Breed.create!(name: 'Akita', size: 3, medium_weight: "23-41kg")
Breed.create!(name: 'Boiadeiro Bernês/Boiadeiro de Berna', size: 3, medium_weight: "38-50kg")
Breed.create!(name: 'Billy', size: 3, medium_weight: "24-35kg")
Breed.create!(name: 'Bloodhound/Cão-de-Santo-Humberto', size: 3, medium_weight: "36-50kg")
Breed.create!(name: 'Boiadeiro de Flandres/Bovier de Flandres', size: 3, medium_weight: "27-40kg")
Breed.create!(name: 'Boxer', size: 3, medium_weight: "25-32kg")
Breed.create!(name: 'Braco Alemão Pelo Curto', size: 3, medium_weight: "20-32kg")
Breed.create!(name: 'Braco Alemão Pelo Duro', size: 3, medium_weight: "27-35kg")
Breed.create!(name: 'Braco Italiano', size: 3, medium_weight: "25-40kg")
Breed.create!(name: 'Bullmastiff', size: 3, medium_weight: "41-59kg")
Breed.create!(name: 'Cane Corso', size: 3, medium_weight: "40-50kg")
Breed.create!(name: 'Cimarrón Uruguayo', size: 3, medium_weight: "33-45kg")
Breed.create!(name: 'Collie', size: 3, medium_weight: "18-29kg")
Breed.create!(name: 'Dálmata', size: 3, medium_weight: "15-32kg")
Breed.create!(name: 'Dobermann', size: 3, medium_weight: "32-45kg")
Breed.create!(name: 'Dogo Argentino', size: 3, medium_weight: "35-45kg")
Breed.create!(name: 'Dogo Canário', size: 3, medium_weight: "40-59kg")
Breed.create!(name: 'Dogue de Bordeaux', size: 3, medium_weight: "54-65kg")
Breed.create!(name: 'Foxhound Americano', size: 3, medium_weight: "20-34kg")
Breed.create!(name: 'Foxhound Inglês', size: 3, medium_weight: "25-35kg")
Breed.create!(name: 'Galgo Espanhol', size: 3, medium_weight: "23-25kg")
Breed.create!(name: 'Galgo Inglês/Greyhound', size: 3, medium_weight: "27-40kg")
Breed.create!(name: 'Golden Retriever', size: 3, medium_weight: "25-35kg")
Breed.create!(name: 'Husky Siberiano', size: 3, medium_weight: "16-27kg")
Breed.create!(name: 'Labrador retriever', size: 3, medium_weight: "25-36kg")
Breed.create!(name: 'Malamute do Alasca', size: 3, medium_weight: "32-43kg")
Breed.create!(name: 'Pastor Alemão', size: 3, medium_weight: "22-40kg")
Breed.create!(name: 'Pastor Beauceron/Pastor de beauce', size: 3, medium_weight: "30-45kg")
Breed.create!(name: 'Pastor Belga Groenendael', size: 3, medium_weight: "20-35kg")
Breed.create!(name: 'Pastor Belga Malinois', size: 3, medium_weight: "25-35kg")
Breed.create!(name: 'Pastor Bergamasco', size: 3, medium_weight: "26-38kg")
Breed.create!(name: 'Pastor Branco Suiço', size: 3, medium_weight: "25-40kg")
Breed.create!(name: 'Pastor da Ásia Central', size: 3, medium_weight: "40-75kg")
Breed.create!(name: 'Pastor de Brie ou Briard', size: 3, medium_weight: "25-40kg")
Breed.create!(name: 'Pastor Maremano Abruzês', size: 3, medium_weight: "30-45kg")
Breed.create!(name: 'Pastor Polonês de Podhal', size: 3, medium_weight: "30-45kg")
Breed.create!(name: 'Podengo Ibicenco', size: 3, medium_weight: "20-30kg")
Breed.create!(name: 'Pointer Inglês', size: 3, medium_weight: "18-34kg")
Breed.create!(name: 'Poodle standard', size: 3, medium_weight: "22-32kg")
Breed.create!(name: 'Rhodesian Ridgback', size: 3, medium_weight: "29-40kg")
Breed.create!(name: 'Rottweiler', size: 3, medium_weight: "35-60kg")
Breed.create!(name: 'Saluki', size: 3, medium_weight: "15-30kg")
Breed.create!(name: 'Samoieda', size: 3, medium_weight: "17-30kg")
Breed.create!(name: 'Schnauzer gigante', size: 3, medium_weight: "25-48kg")
Breed.create!(name: 'Setter Inglês', size: 3, medium_weight: "25-36kg")
Breed.create!(name: 'Setter Irlândes Vermelho', size: 3, medium_weight: "24-32kg")
Breed.create!(name: 'Sheepdog/Old English Sheepdog', size: 3, medium_weight: "27-45kg")
Breed.create!(name: 'Spinone Italiano', size: 3, medium_weight: "29-39kg")
Breed.create!(name: 'Tosa Inu', size: 3, medium_weight: "36-61kg")
Breed.create!(name: 'Vizla pelo curto/Braco Húngaro de pelo curto', size: 3, medium_weight: "18-29kg")
Breed.create!(name: 'Weimaraner', size: 3, medium_weight: "25-40kg")
Breed.create!(name: 'Afghan Hound/Galgo Afegão', size: 4, medium_weight: "25-34kg")
Breed.create!(name: 'Akita Americano', size: 4, medium_weight: "32-60kg")
Breed.create!(name: 'Borzoi', size: 4, medium_weight: "25-47kg")
Breed.create!(name: 'Cão da Serra da Estrela', size: 4, medium_weight: "30-50kg")
Breed.create!(name: 'Dogue Alemão', size: 4, medium_weight: "45-90kg")
Breed.create!(name: 'Fila Brasileiro', size: 4, medium_weight: "57-82kg")
Breed.create!(name: 'Komondor', size: 4, medium_weight: "40-60kg")
Breed.create!(name: 'Kuvasz', size: 4, medium_weight: "35-52kg")
Breed.create!(name: 'Leonberger', size: 4, medium_weight: "41-75kg")
Breed.create!(name: 'Mastiff', size: 4, medium_weight: "54-100kg")
Breed.create!(name: 'Mastim (Bretão) Espanhol', size: 4, medium_weight: "52-100kg")
Breed.create!(name: 'Mastim Napolitano', size: 4, medium_weight: "50-70kg")
Breed.create!(name: 'Rafeiro do Alentejo', size: 4, medium_weight: "35-50kg")
Breed.create!(name: 'São Bernardo', size: 4, medium_weight: "64-120kg")
Breed.create!(name: 'Terra Nova', size: 4, medium_weight: "45-70kg")
Breed.create!(name: 'Terrier Preto da Rússia', size: 4, medium_weight: "36-68kg")